### ISSUE TITLE
fl2k_gsm file

### ISSUE THREAD

**Issue by scramble45** [steve-m/fl2k-examples#1]
Where do you get the bin file from in this example or do you just supply it the grc file via stdin?
`fl2k_file -s 138e6 /tmp/fl2k_gsm.bin`

**Comment by steve-m** [comment]
You need to open the grc-file in gnuradio-companion and run the flowgraph to generate the samples (fl2k_gsm.bin).

**Comment by scramble45** [comment]
@steve-m perfect thanks
